services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    # Update envs in the docker file instead
    # environment:
    #   VITE_API_BASE_URL: http://https://fantastic-orbit-5pw55g49gr4f47vp-8080.app.github.dev/
    #   VITE_WS_BASE_URL: ws://https://fantastic-orbit-5pw55g49gr4f47vp-8080.app.github.dev//ws
