services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8080
      VITE_WS_BASE_URL: ws://localhost:8080/ws

volumes:
  db_data: